version: '3.8'

services :
  api:
    container_name: api-prod
    image: api-prod
    build:
      dockerfile: Dockerfile
      context: ./api
      target: production
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      - api
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "spacecorner"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spacecorner.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8000
    image: "dpage/pgadmin4:6.1"
    links:
      - "postgres:pgsql-server"
    ports:
      - "8000:8000"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  postgres-data: ~
  pgadmin-data: ~