version: '3.8'

services:
  frontend:
    container_name: frontend-prod
    image: frontend-prod
    build:
      dockerfile: Dockerfile
      target: production
      context: ./frontend
    depends_on:
      - api
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    ports:
      - "80:80"

  admin:
    container_name: admin-prod
    image: admin-prod
    build:
      dockerfile: Dockerfile
      target: production
      context: ./admin
    depends_on:
      - api
    volumes:
      - /admin/node_modules
      - ./admin:/app
    ports:
      - "81:81"
  api:
    container_name: api-prod
    image: api-prod
    build:
      dockerfile: Dockerfile
      context: ./api
      target: production
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "spacecorner"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data: ~
