version: '3.8'

services:
  frontend:
    container_name: frontend-prod
    image: frontend-prod
    build:
      dockerfile: Dockerfile
      target: production
      context: ./frontend
    restart: always
    volumes:
      - ./frontend/nginx/:/etc/nginx/conf.d/:ro
      - /frontend/node_modules
      - ./frontend:/app
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email contact@ceercle.io --expand -d ceercle.io -d www.ceercle.io -d app.ceercle.io -d www.app.ceercle.io --agree-tos