version: '3.8'

services :
  api:
    container_name: api-dev
    image: api-dev
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend-dev
    image: frontend-dev
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    depends_on:
      - api
    ports:
      - "80:3000"

  admin:
    container_name: admin-dev
    image: admin-dev
    build:
      dockerfile: Dockerfile
      context: ./admin
      target: development
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /admin/node_modules
      - ./admin:/app
    depends_on:
      - api
    ports:
      - "81:3000"

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "spacecorner"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spacecorner.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8000
    image: "dpage/pgadmin4:6.1"
    links:
      - "postgres:pgsql-server"
    ports:
      - "8000:8000"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  postgres-data: ~
  pgadmin-data: ~
