export const LOGIN = "/"
export const DASHBOARD = "/dashboard"
export const COMPANY_LIST = "/company"
export const COMPANY_DETAILS = "/company/:id"
export const OFFICE = "/company/:id/office"
export const OFFICE_ELEMENT = "/company/:id/office/:idOffice"
export const TEST = "/test"